version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install -e ./.
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pyrest -v
            pytest --junitxml=test-reports/junit.xml
      - store-test-results:
          path: test-reports
