version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install pytest-cov
            pip install -e ./.
      - run:
          name: run test1
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reports/junit.xml
      - store-test-results:
          path: test-reports
      - run:
          name: run test2
          command: |
            . venv/bin/activate
            # pytest --junitxml=test-reports/junit.xml
            # pytest --cov=src --cov-report=html:test-reports
            pytest --cov=src
            # pytest --cov=src --cov-report=xml:test-reports
            # pyrest -v
